site_name: Foooo

copyright: <p xmlns:cc="http://creativecommons.org/ns#" >Unless otherwise declared, this work is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a></p>

nav:
  - "首页":
    - index.md
  - "基础知识": 
    - basic/index.md
    - "术语表": basic/terms.md
    - "Node.JS": basic/nodejs.md
    - "Termux": basic/termux.md
  - "聊天": 
    - "聊天工具和知识概览": chatting/index.md
    - "取得 API 密钥":
      - "概览": chatting/api_connection/index.md
      - "OpenAI":
        - "OpenAI Platform": chatting/api_connection/oai.md
        - "Azure OpenAI Service": chatting/api_connection/azure.md
      - "Claude":
        - "Anthropic Console": chatting/api_connection/anthropic.md
        - "Google Vertex AI": chatting/api_connection/vertex.md
        - "Amazon Bedrock": chatting/api_connection/bedrock.md
      - "Google Gemini": chatting/api_connection/gemini.md
      - "辅助工具":
        - "Clewd": 
          - "下载和安装": chatting/api_connection/clewd/clewd.md
          - "注册 Claude 帐号": chatting/api_connection/clewd/account.md
          - "订阅 Claude Pro": chatting/api_connection/clewd/pro.md
          - "获取 Cookie": chatting/api_connection/clewd/cookie.md
          - "Clewd 常见问题": chatting/api_connection/clewd/faq.md
        - "oai-reverse-proxy": chatting/api_connection/oai_reverse_proxy.md
        # - "OneAPI": chatting/api_connection/index.md
    - "SillyTavern（酒馆）": 
        - "酒馆简介": chatting/sillytavern/index.md
        - "安装": chatting/sillytavern/install.md
        - "连接到 LLM": chatting/sillytavern/api_connect.md
        - "获取聊天预设": chatting/sillytavern/get_preset.md
        - "获取角色卡和周边信息": chatting/sillytavern/get_resource.md
        - "开始聊天": chatting/sillytavern/chat.md
        - "常见问题": chatting/sillytavern/faq.md
  - "绘画":
    - drawing/index.md
  - "其它资源":
    - resources/index.md

extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html

theme:
  name: material
  language: zh
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
  palette:
    primary: orange
    accent: amber
