site_name: AI 巨大娘会梦见电子小人吗
site_url: https://gtss-ai-docs.barz.foo

copyright: <p xmlns:cc="http://creativecommons.org/ns#" >Unless otherwise declared, this work is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a></p>

nav:
  - "首页":
    - index.md
  - "基础知识": 
    - basic/index.md
    - "术语表": basic/terms.md
    - "Node.js": basic/nodejs.md
    - "Termux": basic/termux.md
  - "聊天": 
    - "聊天工具和知识概览": chatting/index.md
    - "预防欺诈": chatting/avoid_scamming.md
    - "取得 API 密钥":
      - "概览": chatting/api_connection/index.md
      - "OpenAI":
        - "OpenAI Platform": chatting/api_connection/oai.md
        # - "Azure OpenAI Service": chatting/api_connection/azure.md
      - "Claude":
        - "Anthropic Console": chatting/api_connection/anthropic.md
        # - "Google Vertex AI": chatting/api_connection/vertex.md
        # - "Amazon Bedrock": chatting/api_connection/bedrock.md
      - "Google Gemini": chatting/api_connection/gemini.md
      - "辅助工具":
        - "Clewd": 
          - "下载和安装 Clewd": chatting/api_connection/clewd/clewd.md
          - "注册 Claude 帐号": chatting/api_connection/clewd/account.md
          - "订阅 Claude Pro": chatting/api_connection/clewd/pro.md
          - "获取 Cookie": chatting/api_connection/clewd/cookie.md
          - "Clewd 常见问题": chatting/api_connection/clewd/faq.md
        - "oai-reverse-proxy": chatting/api_connection/oai_reverse_proxy.md
        # - "OneAPI": chatting/api_connection/index.md
    - "SillyTavern（酒馆）": 
        - "酒馆简介": chatting/sillytavern/index.md
        - "聊天快速上手":
          - "安装": chatting/sillytavern/install.md
          - "杂鱼用一键脚本":
            - "Termux": chatting/sillytavern/termux_deployment_script/index.md
          - "连接到 LLM": chatting/sillytavern/api_connect.md
          - "获取角色卡和关联信息": chatting/sillytavern/get_char.md
          - "获取对话补全预设": chatting/sillytavern/get_preset.md
          - "获取其它周边信息": chatting/sillytavern/get_resource.md
          - "开始聊天": chatting/sillytavern/chat.md
          - "常见问题": chatting/sillytavern/faq.md
  # - "绘画":
  #   - drawing/index.md
  # - "其它资源":
  #   - resources/index.md

extra_css:
  - stylesheets/extra.css

plugins:
  - privacy
  - search
  - glightbox
  - offline

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.annotate 
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


repo_url: https://github.com/foobarz076/gtss_ai_docs
repo_name: foobarz076/gtss_ai_docs